# Cloud Build configuration para deploy automático

steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/seu-assistente-financeiro:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/seu-assistente-financeiro:latest'
      - '.'

  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/seu-assistente-financeiro:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/seu-assistente-financeiro:latest'

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'seu-assistente-financeiro'
      - '--image'
      - 'gcr.io/$PROJECT_ID/seu-assistente-financeiro:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/seu-assistente-financeiro:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/seu-assistente-financeiro:latest'

timeout: '1200s'

